name: finance_guardian
description: "AI Powered Personal Finance Guardian App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.4

  # SMS
  flutter_sms_inbox: ^1.0.4
  permission_handler: ^12.0.1

  # Charts
  fl_chart: 0.63.0

  # Utils
  intl: ^0.18.1
  http: ^1.1.0

  # Splash
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
